apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "classquiz.fullname" . }}-postgresql
  labels:
    {{- include "classquiz.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgresql.persistence.size | quote }}
  storageClassName: {{ .Values.global.storageClass }}