apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: classquiz-frontend
spec:
  host: classquiz.example.com
  to:
    kind: Service
    name: classquiz-frontend
  port:
    targetPort: 80
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect