apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: classquiz-frontend
spec:
  source:
    type: Git
    git:
      uri: https://github.com/erwangranger/ClassQuiz.git
      ref: main
    contextDir: frontend
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: DockerImage
        name: docker.io/library/node:20
  output:
    to:
      kind: ImageStreamTag
      name: classquiz-frontend:latest
  triggers:
    - type: ConfigChange
    - type: ImageChange
    - type: GitHub
      github:
        secret: github-webhook-secret